### ISSUE TITLE
Where does the files I upload go?

### ISSUE THREAD

**Issue by bendini20** [mtlynch/picoshare#109]
I may be missing something, but I would like to specify where exactly the files are stored that I upload to picoshare. If this is not already a feature, I would love for it to be added.

**Comment by mtlynch** [comment]
Thanks for checking it out! You can specify the data path with the `db` flag:

https://github.com/mtlynch/picoshare#command-line-flags

It's worth noting that PicoShare stores all file data in the SQLite database, so you won't see the files themselves on the filesystem.

When running in Docker, PicoShare writes to `/data/store.db`, but you can use Docker volume mounts to redirect that to any path on your host system.

**Comment by bendini20** [comment]
Thank you for the explanation. Are there any plans in the future to allow Postgres or MariaDB integration? Using SQLite has much worse performance than an external database.

**Comment by mtlynch** [comment]
MySQL and Postgres beat SQLite at scale, but for small loads, SQLite is [competitive if not faster](https://blog.wesleyac.com/posts/consider-sqlite).

PicoShare is optimized for simplicity and ease of deployment, so I'm planning to stick with SQLite, since it great in that regard.

**Comment by bendini20** [comment]
That makes sense. Thanks for the quick response.

**Comment by bendini20** [comment]
I would like to see a progress percentage and speed so I can see how my file upload is doing.

**Comment by bendini20** [comment]
Thank you!
