### ISSUE TITLE
Error when uploading files >5GB

### ISSUE THREAD

**Issue by dnburgess** [mtlynch/picoshare#122]
While testing to see max file size support, was able to upload files larger than 1GB, but when uploading a file approximately 6GB, I received this error message in the browser:

> Failed to communicate with server: Failed to fetch

When looking through Docker logs, I found this:

> 2022/03/23 13:32:44 upload.go:51: error reading body: multipart: NextPart: http: request body too large

**Comment by mtlynch** [comment]
Thanks for reporting this, @dnburgess!

This is fixed in #103, but I haven't cut a new release with the fix yet.
