### ISSUE TITLE
Remove row after delete?

### ISSUE THREAD

**Issue by dertuerke** [mtlynch/picoshare#138]
Do we need to remove the row after delete the file?
Currently, the link/file is deleted but the row is still displayed. Only after a reload of the page, the row is gone.

**Comment by mtlynch** [comment]
Yeah, this was just laziness on my part. We could have it delete with an animation or something. I just didn't want to have it disappear as soon as you clicked the button.

**Comment by dertuerke** [comment]
Ok. I can try to animate it 👍
