### ISSUE TITLE
Shorten URLs with external tool

### ISSUE THREAD

**Issue by the-hotmann** [mtlynch/picoshare#161]
The included link shortener is pretty handy, but there are many other FOSS projects that do exactly this, just:

1. better
2. with more features
3. with tracking
4. API-based
5. etc etc etc

Thanks why I would like to ask, if you guys could think of connecting this to "[Shlink](https://github.com/shlinkio/shlink)" or if that would be no option?

Thanks in advance!

**Comment by mtlynch** [comment]
How do you imagine it integrating with shlink?

**Comment by MartinHotmann** [comment]
Through the API of Shlink you can create Shlinks (short links) which point to the URL PicoShare just created.
The Shlink then should displayed just like the shortURL from PicoShare next to the longURL. Or even replacing the shortURL from PicoShare.

Just a thought..

**Comment by dertuerke** [comment]
I see it more as a manual task. In my opinion, this has nothing to do with Picoshare.
Picoshare only provides you with a link, what you do with it in the end is your business.

**Comment by mtlynch** [comment]
Oh, gotcha. I can see the value, but I agree with @dertuerke that it's a little outside the scope of PicoShare. We can keep the bug open to see if there's interest.

**Comment by mtlynch** [comment]
From reflecting on this a bit more, I'm afraid I'm going to close this as out of scope. I've written up a bit more about what I consider in scope for PicoShare:
