### ISSUE TITLE
Support custom expiration times

### ISSUE THREAD

**Issue by MasterChiefv1** [mtlynch/picoshare#163]
Hi, 

Wanna say great app, keep it up.
Can we also have the ability to delete file in couple of hours? options like 30 min, 1 hour and 5 hours?

Thanks.

**Comment by mtlynch** [comment]
Yeah, I'd like to add a "Custom" option where you can pick arbitrary expiration times with a date picker.

**Comment by MasterChiefv1** [comment]
Yeah, that will be great.
Thanks and keep it up.
