### ISSUE TITLE
Filename with over 100 characters does not upload

### ISSUE THREAD

**Issue by tanmay-pathak** [mtlynch/picoshare#181]
First of all good work on this project and the latest update on arm images. 

## Bug
Currently, picoshare allows the user to upload a file with under 100 character filenames (including `.` and the extension). Anything over 100 characters results in the following error: `can't read request body: filename too long`

## How to replicate
- Create a `.txt` file with a filename of 97 characters. E.g: `pQmvFuKknUjALPLSIuIuqdgKDVN8xAo2MYEKAxjfURW5JQ858qrQtvxxAmdizK5ILlRKm8McQwGTHAWb180P0ttVscosNPJc4.txt`
- Try to upload this newly created file and you should encounter this error.

## Possible solution
- Maybe a check and some way to automatically shorten/truncate the filename.

**Comment by mtlynch** [comment]
Thanks for the feedback!

The limit is just arbitrary:

https://github.com/mtlynch/picoshare/blob/a693ca25824304ec27f9f5cdfe0f95bc6141ae5b/handlers/upload.go#L18

I wanted to pick some upper bound to limit damage from a malicious user, but it can really be any number we want.

What kind of files do you have that have 100+ character filenames? Is there a different upper-bound that would let you upload what you need without accepting filenames of arbitrary length?

**Comment by tanmay-pathak** [comment]
Oh, that is good to know. 

I have found books and articles usually have long file names with author, title, publisher details etc. Maybe a 150 upper-bound would be a reasonable tradeoff.

**Comment by mtlynch** [comment]
@tanmay-pathak - Thanks, fixed! It'll be available in 1.0.7, which is building now.
