### ISSUE TITLE
Too much memory (docker)

### ISSUE THREAD

**Issue by wisinfun** [mtlynch/picoshare#182]
It takes up a lot of memory when uploading and downloading files

It always takes a long time to respond when downloading

Why not consider storing files in folders? I always feel that SQLite will have performance problems

**Comment by mtlynch** [comment]
I'm planning to stick with SQLite for the foreseeable future because it gives us cloud replication essentially for free through Litestream. If we switch to static files, we have to manage our own replication.

**Comment by mtlynch** [comment]
@wisinfun - The [1.2.0 release](https://github.com/mtlynch/picoshare/releases/tag/1.2.0) includes several fixes for reducing TinyPilot's RAM footprint. More details on my blog:

https://mtlynch.io/notes/picoshare-perf/
