### ISSUE TITLE
Serve admin interface from its own location prefix

### ISSUE THREAD

**Issue by satwell** [mtlynch/picoshare#242]
I'd love to run picoshare with stronger access control than just a shared password for admin functions.  But rather than ask picoshare to add things like IP restrictions or 2FA, I think it would make more sense to do this with a reverse proxy like nginx in front of picoshare.

To make this easier, it would be helpful if picoshare had all of its admin functionality under a URL prefix like `/admin`.  This would make it relatively straight-forward to, for example, restrict admin functions to just specific IPs while allowing all IPs to fetch uploaded files.  Or possibly even put admin URLs behind something like oauth2-proxy or Pomerium.

I think this could technically be done today by having a reverse proxy allow public access to all locations starting with `/!` or `/g/` (plus js, css, etc.).  And then restricting other URLs.  But having a separate `/admin` prefix would make for a much cleaner and less fragile config.

**Comment by mtlynch** [comment]
Most of the routes are admin-only, so I think it'd be cleaner to just whitelist a handful of prefixes and treat the others as forbidden.

The whitelist would be:

```
/
/login
/!*
/g/*
/api/guest/*
/css/*
/js/*
/third-party/*
```

And then the routes related to favicon:

```
/android-chrome-192x192.png
/android-chrome-384x384.png
/apple-touch-icon.png
/browserconfig.xml
/favicon-16x16.png
/favicon-32x32.png
/favicon.ico
/mstile-150x150.png
/safari-pinned-tab.svg
/site.webmanifest
```
