### ISSUE TITLE
Public domain behind Nginx Proxy Manager

### ISSUE THREAD

**Issue by johannmx** [mtlynch/picoshare#255]
hello! I recently deployed through docker and then assigned a public domain through Nginx Proxy Manager but when generating the link it shows the following error message:

![image](https://user-images.githubusercontent.com/63032152/168200645-be15d368-25cb-40b6-b7d8-5f32c10cb4d6.png)

![image](https://user-images.githubusercontent.com/63032152/168201038-dc04967c-fa6b-4329-ab69-d7959c76c4db.png)

But through the browser by internal IP it creates the link and I can then copy it from "files".

![image](https://user-images.githubusercontent.com/63032152/168200870-539b2482-005e-43f8-9a3b-091151ec549f.png)

And this message is from a mobile browser:

![image](https://user-images.githubusercontent.com/63032152/168225206-edfa59b3-a7bc-4501-a498-80c99a6bc2a2.jpeg)

hope you can helpme!

thanks!

**Comment by mtlynch** [comment]
Thanks for reporting this!

Do you see any errors in your browser's JavaScript console?

**Comment by johannmx** [comment]
> Thanks for reporting this!
> 
> 
> 
> Do you see any errors in your browser's JavaScript console?

Hi thanks for your reply! 

No I dont see any errors in the console.

My setup is:

- Docker
- Cloudflare DNS
- Nginx Proxy Manager with Cloudflare Wildcard SSL Certificate
- URL is under "share.domain.com"

**Comment by mtlynch** [comment]
It seems like it might be related to CSP. What version are you on? Can you try upgrading to [1.1.6](https://github.com/mtlynch/picoshare/releases/tag/1.1.6)? If you're still seeing the issue, you can also try rolling back to [1.1.3](https://github.com/mtlynch/picoshare/releases/tag/1.1.3) which essentially disables CSP.

**Comment by johannmx** [comment]
> It seems like it might be related to CSP. What version are you on? Can you try upgrading to [1.1.6](https://github.com/mtlynch/picoshare/releases/tag/1.1.6)? If you're still seeing the issue, you can also try rolling back to [1.1.3](https://github.com/mtlynch/picoshare/releases/tag/1.1.3) which essentially disables CSP.

Hi! latest version (latest tag) and upgraded to 1.1.6 and nothing happend.

Rolling back to 1.1.3 and this message appears

![image](https://user-images.githubusercontent.com/63032152/170056570-b84df9b0-d777-46a7-a62c-af7dd0085a0e.png)

**Comment by johannmx** [comment]
Hi problem solved updated the container to the last version and now I can upload files behind NPM!

**Comment by mtlynch** [comment]
Oh, great! Thanks for letting me know.

**Comment by gabrySerra** [comment]
> Hi problem solved updated the container to the last version and now I can upload files behind NPM!

Hey!
Do you have 100MB limit by Cloudflare? I'm not able to upload big file.
