### ISSUE TITLE
Memory usage increasing proportionally with upload size

### ISSUE THREAD

**Issue by raisinbear** [mtlynch/picoshare#260]
Hi,

first thanks for all the work and for creating this project! I like the minimalist approach that still includes all functionality I wish for in this kind of service.

I gave the docker container a try and the only thing keeping me from deploying on my low-spec machine is that memory consumption increases pretty much by the upload size of the file. I tried with three test files, 100M each. Memory consumption had gone up by 300M after the last upload. I don't know if and when memory is freed again, but it didn't within 10 minutes or so. Even if it was freed within a reasonable timeframe, uploads could easily consume all memory on my machine and lead to OOM or at least intense swapping, which shouldn't be the case.

**Comment by mtlynch** [comment]
Thanks for reporting this!

I'm not sure why it's consuming so much memory. I suspect it has to do with sqlite not normally being used to store this much data, but it's possible the leak is on my side.

I've successfully tested a workaround in limiting memory to the Docker container. For example, this would run PicoShare with a max of 256 MB of RAM:

```bash
docker run \
  --env "PORT=3001" \
  --env "PS_SHARED_SECRET=somesecretpass" \
  --memory "256m" \
  --publish 3001:3001/tcp \
  --volume "${PWD}/data:/data" \
  --name picoshare \
  mtlynch/picoshare
```

In my tests, it runs successfully even with large files.

**Comment by raisinbear** [comment]
Thanks for the quick reply (and sorry for getting back so late)!
I'll give the memory limit a try and see how low I can push it. For context, I'm planning on running this on a raspberry pi which I am already pushing to its limits. Apart from this issue, Picoshare would be the perfect solution due to being very lightweight (while in my opinion very well designed :). Ideally, I'd like to keep memory consumption of this service as close to freshly started state as possible 😅
Should I close this issue?

**Comment by mtlynch** [comment]
We can keep it open because I would like to find a way to reduce the memory footprint without having to add constraints with Docker.

**Comment by mtlynch** [comment]
The RAM footprint should be significantly lower in the 1.2.0 release:

https://github.com/mtlynch/picoshare/releases/tag/1.2.0
