### ISSUE TITLE
Add support for VACUUM (SQLite) when files are deleted from WebGUI

### ISSUE THREAD

**Issue by SmartPhoneLover** [mtlynch/picoshare#272]
Currently, when a file is deleted from the WebGUI, the space taken by that file stills remain in the DB.
So, if possible, implementing VACUUM somewhere in the code when a file is deleted, it will free up memory.

**Comment by mtlynch** [comment]
Thanks! Yes, this was fixed in #212. The VACUUM happens every 7 hours.
