### ISSUE TITLE
Invalid shared secret

### ISSUE THREAD

**Issue by faptaincrunch** [mtlynch/picoshare#274]
When using docker image 1.0.2 I can login but when using any newer image I receive "Invalid shared secret". Changing password doesn't work and I receive the same error. 

When creating a new container and starting fresh I receive the same error, reverting back to 1.0.2 works again. 

https://pastebin.com/gp9pgWpk

**Comment by mtlynch** [comment]
Can you share the command you're using to launch it from Docker? You can change it to a different shared secret for privacy.

The end-to-end tests run on each commit and verify that unlock with shared secret works, so there must be something unique here:

https://user-images.githubusercontent.com/7783288/178163033-55fac118-2074-4404-bb5e-773d369fc0c5.mp4

Is it possible that your shared secret has special characters that are being interpreted by your shell? Make sure you're putting it in quotes.

**Comment by mtlynch** [comment]
Closing due to lack of response, but feel free to reopen if you continue to hit this.
