### ISSUE TITLE
How to change Title ??

### ISSUE THREAD

**Issue by cphpi** [mtlynch/picoshare#275]
hello guys
i have question how can i change the title ? i saw folder templates and base.html here has {{ .Title }}
where can i change it? i'm hosting by docker!
thx

**Comment by mtlynch** [comment]
Unfortunatley, PicoShare doesn't offer ways to change the title through configuration options. You could change the title, but you'd have to make the changes in Go code and recompile from source. You couldn't do this through Docker alone.
