### ISSUE TITLE
Eliminate large transactions to reduce RAM consumption

### ISSUE THREAD

**Issue by danwilhelm** [mtlynch/picoshare#284]
I noticed on @mtlynch's Twitter that [he was investigating large memory usage](https://twitter.com/deliberatecoder/status/1552438652537835521). I thought I'd take a quick look tonight and share some validated fixes. 

I was fortunate to immediately replicate the memory bug in Ubuntu (WSL). I found three scenarios that consume unexpectedly large amounts of RAM -- (1) serving files, (2) parsing the multipart form, and (3) copying the file into sqlite. I'll walk through the likely causes+fixes of these large allocations below:

### ~~1. Serving Files~~

**mtlynch**: Fixed in #285

When serving a file via HTTP, the memory usage increases by ~ the file size.

In **reader.go**, `populateBuffer()` often allocates enough memory for the entire file. Why? The Reader (surprisingly?) only reads a single chunk at a time (to see this, log `startChunk`), but the function retrieves the entire remaining file every time! This results in the retrieval time being $O(s^2)$ with respect to the file size $s$ -- i.e. huge files are very slow to retrieve. And, it requires memory equal to the file size.

For a quick fix, we can limit the amount read from sqlite to a single chunk. (The Reader seems to ignore the rest in my environment at least.) [In the `populateBuffer()` SQL statement](https://github.com/mtlynch/picoshare/blob/fa744dbbd68eae8a306cb60df25deeb337c6f87c/store/sqlite/file/reader.go#L98), change `chunk_index>=?` to `chunk_index=?`. In my case, this resulted in large files being served vastly faster -- and only requires one chunk-size of RAM total. (NOTE: I'm not sure exactly why the Reader reads one chunk at a time -- it could differ based on the environment?)

### ~~2. Parsing the multipart form~~

**mtlynch**: Fixed in #287

EDIT: I have since read the entire Twitter thread, and this optimization was found earlier -- see [here](https://github.com/mtlynch/picoshare/pull/283).

I am seeing ~100MB usage here for large files. The culprit is `ParseMultipartForm()`. `maxMemory` is currently set at `32 << 20 ~= 33MB`. However, [due to the way buffering is done, >100MB can be required to read this 33MB in](https://stackoverflow.com/questions/30657454/multipart-form-uploads-memory-leaks-in-golang).

The solution is just to [reduce the `maxMemory` parameter](https://github.com/mtlynch/picoshare/blob/54fd210a7f1b530b49cae2ff15697acffc4ef4bc/handlers/upload.go#L246), which then also uses smaller buffers. I reduced this to `2 << 20 ~= 2MB` and see about ~10MB memory usage total, instead of 100MB. (NOTE: The memory doesn't seem to be reclaimed after processing, but I didn't investigate why -- probably just a delayed GC?)

### 3. Writing to sqlite
When writing the file to sqlite, the memory usage increases by ~ the file size. (Note: This at least seemed to happen when I disabled caches, disabled journaling, and switched synchronous to FULL. I seemed to avoid this problem w/ the project's pragmas after implementing the above fixes.) 

This is likely caused because an _in-progress transaction_ is passed to the Writer in **writer.go** ([`tx` is a `wrapped.SqlTx`](https://github.com/mtlynch/picoshare/blob/fa744dbbd68eae8a306cb60df25deeb337c6f87c/store/sqlite/file/writer.go#L11)!). So [when `flush()` is called](https://github.com/mtlynch/picoshare/blob/fa744dbbd68eae8a306cb60df25deeb337c6f87c/store/sqlite/file/writer.go#L57), the INSERT (including the entire chunk) is not immediately executed. Instead, it is cached until the final `Commit()` -- way [at the end of `InsertEntry()`](https://github.com/mtlynch/picoshare/blob/22c8ad51c73ffdc05bc0aa06ecedc2a0ce20bc09/store/sqlite/sqlite.go#L293) in **sqlite.go**.

So, all of the chunks are possibly retained in memory (comprising the entire file content) until the very end, making the RAM usage increase by at least the file size. 

I ran out of time to test this theory, but the solution would be to try executing each INSERT query immediately (i.e. the typical meaning of "flush"). Also of note: my WAL file grew extremely large, so it might be interesting to test the other journaling options and to also [increase the page size to 8192 or 16384 for best BLOB I/O](https://www.sqlite.org/intern-v-extern-blob.html).

---

This is my first time using Go, and I only tested it on Ubuntu (WSL). So, it's possible these solutions may not work well on all systems, or even that there are deeper problems (e.g. undiscovered memory leaks). Hopefully these are helpful -- good luck!

**Comment by mtlynch** [comment]
@danwilhelm - Wow, this is great! Thanks so much!

Did you have a good way of measuring when RAM was bloating? One of the issues that I've had is that my test loop involves pushing to fly.io and watching metrics there, which is very slow. I'll try again reproducing it locally, but I'm curious if you found any tools helpful.

**Comment by danwilhelm** [comment]
I got lucky -- was able to replicate the issue first try using Ubuntu on Windows Subsystem for Linux (WSL). 

I manually monitored the memory using `htop`. Then just read through the code that bloated the memory. This was doable here since the memory bloat was so large. 

Glad the SQL fix helped! I held off on a PR since I wasn't sure if the >= was intentional.

**Comment by danwilhelm** [comment]
@mtlynch On your recent commit, I think you switched over most of the SQL queries to immediate execution. However I believe you missed the INSERT I mentioned above which I narrowed down the bloat to. 

Look at this InsertEntry() function: https://github.com/mtlynch/picoshare/blob/22c8ad51c73ffdc05bc0aa06ecedc2a0ce20bc09/store/sqlite/sqlite.go#L250

At the very bottom, there is tx.Commit(). This executes the INSERT statements for all of the chunks, which are added to the transaction in this flush() function: https://github.com/mtlynch/picoshare/blob/fa744dbbd68eae8a306cb60df25deeb337c6f87c/store/sqlite/file/writer.go#L57

Instead of passing wrapper.SqlTx into the writer, I'd suggest trying to pass the db itself and execute each INSERT immediately instead of a huge transaction.

**Comment by mtlynch** [comment]
@danwilhelm - Which commit are you seeing? My most recent one is here:

https://github.com/mtlynch/picoshare/commit/c9a908f804d794f782792c21a08d50dbe42a8e8d#diff-3ed9268b20203e8ecaeebea2b3fea94a09b85036462457126c49425dbf2eb586

My current thinking (from help on Twitter) is that the [RAM bloat is actually okay](https://twitter.com/deliberatecoder/status/1553773360060014593) as long as we don't see OOM because RAM bloat can just be effective use of the page cache.

I tested the transactionless implementation you suggested, and that had no OOM, so that's good news.

I want to do more testing to see which parts of my changes are essential to the fix, because [repro-no-tx](https://github.com/mtlynch/picoshare/tree/repro-no-tx) is currently a hodgepodge of lots of different theories.

**Comment by danwilhelm** [comment]
Good catch (and nice job) -- I missed that! Glad there's no OOM so far with the many theories in place. I think in general there are many possible reasons for RAM usage that could be healthy (in fact the GC might just be waiting to deallocate or reuse it). 

That said, I would stay away from requiring allocations proportional to the size of the file, since I suspect that could eventually cause problems like the OOM.

**Comment by billywhizz** [comment]
what @danwilhelm says makes sense to me. if you are storing files in sqlite db itself and then every page of each file ends up in the wal and needs to be replicated to s3 i wouldn't be surprised if it blows up in many strange ways on a vm with only 256MB. do you have the option to just store the metadata in sqlite and process the files into s3 from the attached storage instead? are you doing any kind of rate limiting on concurrent uploads?

**Comment by mtlynch** [comment]
@billywhizz - Thanks!

>do you have the option to just store the metadata in sqlite and process the files into s3 from the attached storage instead? 

I do, but I made the deliberately wacky decision to store everything in SQLite because it's super convenient to let Litestream replicate all application state without PicoShare having to manage anything itself.

>are you doing any kind of rate limiting on concurrent uploads?

No, not currently.

My next step is to try breaking up the big transaction and tuning the page sizes and see how that affects Litestream.

I suppose I could have some sort of global rate limiter controlling writes to SQLite but that sounds kind of unpleasant, so I'm hoping doing away with transactions makes OOMs unlikely enough that it doesn't come to the point of a global rate limiter.

**Comment by billywhizz** [comment]
tbh - i am not sure how sqlite works with WAL for large blobs like this. my understanding is WAL will only be written when a transaction commits, but i may be wrong on this. i might have to do some testing myself! looking forward to seeing what you discover.
