### ISSUE TITLE
Show guest upload link label in file index

### ISSUE THREAD

**Issue by RVL-Solutions** [mtlynch/picoshare#316]
When a guest link is created, there is the optional label/note field that can be assigned.
It would be great to have that assigned note linked to the file that gets uploaded through the guest link and be visible on the file index!

**Comment by DanMundy** [comment]
Just came here to say this, but it's already logged, so adding my +1

And thanks for a great little app! It's almost perfect at what it does :)

**Comment by Woahai321** [comment]
Im not sure of the implications, but the easiest way I was able to accomplish this was to remove the following code from the handlers/upload.go

`	if guestLinkID != "" && note.Value != nil {
		return picoshare.EntryID(""), errors.New("guest uploads cannot have file notes")
	}`
	
and then append the guest upload in the js/controllers/files.js

`export async function guestUploadFile(file, guestLinkID, progressFn) {
  const formData = new FormData();
  formData.append("file", file);
  formData.append("note", `Guest File - ${guestLinkID}`);
  return uploadFormData(`/api/guest/${guestLinkID}`, formData, progressFn);
}`

You can also add the link ID as a column in the guest links index.html

![image](https://user-images.githubusercontent.com/115117306/235564288-c2a9b668-0151-4de6-a36c-4038ff6e6087.png)

![image](https://user-images.githubusercontent.com/115117306/235564372-02fec564-a3bb-498e-832c-7c229d5292de.png)

**Comment by Woahai321** [comment]
> Im not sure of the implications, but the easiest way I was able to accomplish this was to remove the following code from the handlers/upload.go
> 
> ` if guestLinkID != "" && note.Value != nil { return picoshare.EntryID(""), errors.New("guest uploads cannot have file notes") }`
> 
> and then append the guest upload in the js/controllers/files.js
> 
> `export async function guestUploadFile(file, guestLinkID, progressFn) { const formData = new FormData(); formData.append("file", file); formData.append("note", `Guest File - ${guestLinkID}`); return uploadFormData(`/api/guest/${guestLinkID}`, formData, progressFn); }`
> 
> You can also add the link ID as a column in the guest links index.html
> 
> ![image](https://user-images.githubusercontent.com/115117306/235564288-c2a9b668-0151-4de6-a36c-4038ff6e6087.png)
> 
> ![image](https://user-images.githubusercontent.com/115117306/235564372-02fec564-a3bb-498e-832c-7c229d5292de.png)

Can also do it like this which I think I like better

![image](https://user-images.githubusercontent.com/115117306/235567440-d979dbb1-51f3-4008-aa71-c14cead0cc5e.png)

**Comment by mtlynch** [comment]
Thanks! I'll think more about how to implement this.

**Comment by Woahai321** [comment]
> Thanks! I'll think more about how to implement this.

For someone who doesn't know how to code, GPT does wonders 😂👍

**Comment by mtlynch** [comment]
Fixed in #473, which shows the guest link label on the file info page.
