### ISSUE TITLE
Feature Request: Add a setting to make notes mandatory

### ISSUE THREAD

**Issue by RVL-Solutions** [mtlynch/picoshare#317]
Make it possible to set note/labels to mandatory instead of optional.
Would be really useful!

**Comment by mtlynch** [comment]
From reflecting on this a bit more, I'm afraid I'm going to close this as out of scope. I've written up a bit more about what I consider in scope for PicoShare:

https://github.com/mtlynch/picoshare#picoshares-scope-and-future
