### ISSUE TITLE
[Feature request] Automatically import files from shared folder

### ISSUE THREAD

**Issue by jaapiyo** [mtlynch/picoshare#344]
Awesome work on Picoshare! 

It's currently running on my TrueNAS Scale server and I was wondering if it's possible to automatically import all files in a special directory? That way I don't have to upload them to my own server (were the files already are anyway). It also helps my workflow for releasing large files to my customers.

**Comment by mtlynch** [comment]
Thanks for the kind words!

I'm not likely to support any kind of importing from the filesystem, as it's too far outside the scope of what I'd like PicoShare to be, but there are ways of auto-importing a directory that might work for you instead.

If you generate a guest link, you can [upload from the command line](https://github.com/mtlynch/picoshare/issues/100#issuecomment-1213628894), so you can do it like this:

1. Generate a guest link in your PicoShare server
2. Copy the ID portion of the guest link (the last part of the URL, after the `/g/`)
3. Open a bash terminal session
4. Navigate to the directory you want to upload
5. Run the following snippet:

```bash
PICOSHARE_BASE_URL="http://127.0.0.1:4001" # Replace with your PicoShare server's address
GUEST_LINK_ID="gi7g6t9UcBCX6jv4"           # Replace with your guest link ID

for file in *; do
  curl -F "file=@${file}" "${PICOSHARE_BASE_URL}/api/guest/${GUEST_LINK_ID}"
done
```

That will iterate through your files and import them to PicoShare.
