### ISSUE TITLE
Possibilty to mount a temp folder in docker

### ISSUE THREAD

**Issue by keppo070** [mtlynch/picoshare#352]
It seems that while uploading the file is first stored in /var/lib/docker. Is there a possibility to mount another location for storing the temporary file before it is included in the sqlite file

**Comment by mtlynch** [comment]
PicoShare using Go's standard library for storing uploaded data as it arrives, which I believe is just `/tmp`, so you could mount the container's `/tmp` path to a different location on your host like:

```bash
docker run \
  --env "PORT=3001" \
  --env "PS_SHARED_SECRET=somesecretpass" \
  --publish 3001:3001/tcp \
  --volume "${PWD}/data:/data" \
  --volume "/path/to/some/upload/location:/tmp" \
  --name picoshare \
  mtlynch/picoshare
```
