### ISSUE TITLE
Default PORT is 4001, not 3001

### ISSUE THREAD

**Issue by Zaczero** [mtlynch/picoshare#358]
Documentation issue:

https://github.com/mtlynch/picoshare/blob/bdc861ebe05be8a8be0e8cdc8e854851eede0e6a/README.md?plain=1#L114

https://github.com/mtlynch/picoshare/blob/bdc861ebe05be8a8be0e8cdc8e854851eede0e6a/cmd/picoshare/main.go#L47-L51

**Comment by mtlynch** [comment]
Thanks! Fixed in #359.
