### ISSUE TITLE
Can't find full link for previously uploaded files

### ISSUE THREAD

**Issue by plasticmae** [mtlynch/picoshare#373]
When I file is uploaded it provides two links, the full link with the file extension and the shortened one. However, after I leave that page, I can't find a way to get the full link from my list of files, just the short link. Sometimes, however, I need the full link. Am I just missing a way to get the full link?

**Comment by mtlynch** [comment]
Thanks for reporting that!

Yeah, that's a missing feature. I'm tracking that in #356.
