### ISSUE TITLE
Make it possible to configure 'never' as the default file expiration

### ISSUE THREAD

**Issue by Zaczero** [mtlynch/picoshare#379]
10 years is probably fine, but I would love to live in a perfect world with never expiring files 👍️

possibly set by sending a -1 (negative) value?

**Comment by Zaczero** [comment]
or at least extend max duration to something around 100 years? this would suffice my needs.

**Comment by modem7** [comment]
Unsure if this should be a default though.

Maybe an ENV var value to dictate what we want the defaults to be?

**Comment by Zaczero** [comment]
I believe each person should be able to decide what their default should be.

I don't say that this should be default by default, I just say that it should be possible to configure it. Currently max possible configurable default is 10 years.
