### ISSUE TITLE
FEATURE: ENV vars for DB and Vacuum

### ISSUE THREAD

**Issue by modem7** [mtlynch/picoshare#395]
Instead of having these commands as CLI options and using `command: -vacuum true -db /data/store.db` or similar, would it be possible to have these options as ENV Vars instead?

E.g.

```yaml
    environment:
      - VACUUM=true
      - DB=/data/store.db
```

**Comment by mtlynch** [comment]
Thanks for filing this!

Can you add a bit of context? Why env vars over CLI flags?

With env vars, you run the risk of conflicting with existing var names in the environment, whereas that's not possible with flags. Flags also have native support in the Go standard library for basic parsing into types, which env vars don't.

**Comment by modem7** [comment]
Heya,

Typically, with Linux env vars, they're all upper case, so to limit/eliminate conflicts, we can set lowercase vars such as db etc. 

I totally understand where you're coming from re the conflicts though, but with the env vars, it opens up the image to further platforms that may restrict users to only using ENVs rather than commands (e.g. creating via Portainer etc etc etc), and it would make the functionality more uniform across the board.

So instead of having xyz in `command` and abc in `environment`, having everything more uniform makes it easier for end users to define non-default variables, and to change them as and when they require.

I'd say that commands vs env can interchangeably be mistyped by users (especially if they're unsure about the relevant commands), but with env, if they've mistyped, the image will still work as intended, except their variable won't be enacted.

E.g. `PS_VACUUM` vs `PS_VACCUUM`.

Whereas if I do the same in a command, the image falls over:

```
++ echo false
+ PS_LAUNCH_CMD='/app/picoshare -vaccuum true -db /data/store.db'
+ [[ false == \t\r\u\e ]]
+ echo 'Starting without litestream'
Starting without litestream
+ eval '/app/picoshare -vaccuum true -db /data/store.db'
++ /app/picoshare -vaccuum true -db /data/store.db
2023/02/06 15:50:46 initializing random seed
2023/02/06 15:50:46 main.go:23: starting picoshare server
flag provided but not defined: -vaccuum
Usage of /app/picoshare:
  -db string
    	path to database (default "data/store.db")
m
    	vacuum database periodically to reclaim disk space
```

**Comment by mtlynch** [comment]
Thanks for sharing those details. I've considered it, but I'd rather stick with command-line flags.

With Portainer and UnRAID, you should be able to still specify command-line flags via the `command` option.

>I'd say that commands vs env can interchangeably be mistyped by users (especially if they're unsure about the relevant commands), but with env, if they've mistyped, the image will still work as intended, except their variable won't be enacted.

I see this as an advantage of flags over environment variables. If the user mistyped the command, we *should* fail fast. I'd rather give them instant feedback that they typed the command wrong than to run and force them to figure out why it's not behaving the way they expect.
