### ISSUE TITLE
inconsistency on upload site

### ISSUE THREAD

**Issue by tanrak** [mtlynch/picoshare#396]
Why are there actually two upload boxes? One labeled "Choose a File..." and the other labeled "Or paste something here". Since drag and drop also works in the first upload box, the second one would not be necessary after all.
Maybe it would make sense to label the first upload box with "Choose or Drag & Drop a File..." and delete the textarea.
By the way, drag and drop does not work under Firefox in the textarea box. In Edge, it works in both boxes.

**Comment by mtlynch** [comment]
Thanks for reporting this!

The text area is for pasting text from the clipboard, which isn't possible in the file upload box.

**Comment by tanrak** [comment]
Thanks for the clarification. Maybe a note about this feature in the readme,md would be useful.
