### ISSUE TITLE
Internal view counter, or even audit log?

### ISSUE THREAD

**Issue by jotaen** [mtlynch/picoshare#401]
I’m wondering whether it’s possible to have an internal view counter for the files, or even an access/audit log that logs IP and timestamp. That would only show up in the admin dashboard, so that you can see what’s going on.

Possible technical implications:

- This would increase write load on the system, particularly for installations with higher traffic. Also not sure how a potential Litestream replica would deal with that.
- It also requires more disk space. For an incremental counter, that’s probably not that big of a problem, but for an audit log (with IP and timestamp) that can be significant data. So the audit log part could also be optional, though that increases the complexity of the implementation.

This idea is tangentially related to https://github.com/mtlynch/picoshare/issues/259.

**Comment by jlpnea** [comment]
hi, I would also like to find this feature, to have this download history

**Comment by cuckovich** [comment]
I'd also like this! Would be great to get a download count
