### ISSUE TITLE
Tips for better streaming performance ?

### ISSUE THREAD

**Issue by didli** [mtlynch/picoshare#404]
Hi ! I'm using picoshare (with podman in fedora 37) to post and share bass cover videos (around 150 to 350 Mo) on a dedicated forum. While I don't think it's a picoshare issue, some forum users reports issues to play and cache the videos (the videos paused every 30 sec or so).
Could you please tell me if there is something I could try to improve this performance problem on "the picoshare side" ?
Thank you for your help !

**Comment by didli** [comment]
That was a PIBKAC issue. The problem being me. I didn't even realize I've uploaded a 1440p video. And a 10000kb/s bitrate, that's not helping. I'm closing this nonexistent issue. Sorry for the noise.

**Comment by mtlynch** [comment]
@didli - Thanks for reporting it! Good to know in case someone runs into something similar.
