### ISSUE TITLE
Videos/Music curled to PicoShare are not playable in the browser.

### ISSUE THREAD

**Issue by Ay1tsMe** [mtlynch/picoshare#427]
If i upload a .mp4 or .mp3 file to picoshare, the video or audo is able to stream within the browser without downloading a local copy.

However, if i curl the video using:
`curl -F"file=@video.mp4" https://picoshare.tuxtower.net/api/guest/example_guest_link`

When i access the file on picoshare, it prompts me to download the file instead of streaming it in the browser. 

curling images works fine and I am able to view them without downloading it to my machine but music and video don't

**Comment by mtlynch** [comment]
Ah, true. It serves the `Content-Type` of however it was uploaded. When you upload a video through the browser, the browser automatically adds `video/mp4` to videos and `audio/mpeg` to mp3s. When you upload with curl, it doesn't add the content type.

Maybe PicoShare can automatically add the correct `Content-Type` header at download time if none was provided by the client at upload time.

In the meantime, you can work around it by specifying the type in the `curl` command like this:

```bash
curl -F"file=@video.mp4;type=video/mp4" https://picoshare.tuxtower.net/api/guest/example_guest_link
```

**Comment by Ay1tsMe** [comment]
I would love if this was a features as I do most of my work in the terminal. It would be nice if picoshare can automatically detect the content-type but in the meantime ill write a quick shell script that works for the content-type.

**Comment by mtlynch** [comment]
@Ay1tsMe - Sure, this is fixed now.

**Comment by Ay1tsMe** [comment]
I don't want to be a pain but when i tried 
`curl -F"file=@video.mp4" https://picoshare.tuxtower.net/api/guest/example_guest_link` 
with the new update, it still doesn't infer the content-type automatically. I'm not sure if i've updated my instance correctly.

I'm running it through docker-compose. I did:
```
docker pull mtlynch/picoshare

docker-compose down

docker-compose up -d
```
Have I updated it correctly to reflect the changes or have I done something wrong?

**Comment by mtlynch** [comment]
Ah, you're right. I didn't realize `curl` actually sets mp3 and mp4 files to a content type of `application/octet-stream`. 

I've fixed this in #434 and cut a new release.

**Comment by Ay1tsMe** [comment]
Okay this mostly works. It seems to play mp3's and mp4's correctly now which is great but other different filetypes that normally work when you upload them in the browser like webm, wav dont seem to be watchable through `curl`. I had a look through the source code and I don't know if its as simple as adding a new case to the downloads.go file for each extension? like this:
```
case ".wav":
    return picoshare.ContentType("audio/wav"), nil
```
Maybe theirs a better way to do this? 
I've also had a look in my sql entries database and I'm not sure if it's intended but when for example I `curl`the mp4 i want to upload, it still says its content-type is application/octet-stream in the entries table instead of video/mp4. But it still works when viewing in the browser, so not sure there.

**Comment by mtlynch** [comment]
>I had a look through the source code and I don't know if its as simple as adding a new case to the downloads.go file for each extension?

Yeah, I just tried a few different types of media to see where curl was omitting the content type and put in overrides in #430 and #434. If you want to contribute other file types and overrides, that should fix the others. It's pretty straightforward.

>I've also had a look in my sql entries database and I'm not sure if it's intended but when for example I curlthe mp4 i want to upload, it still says its content-type is application/octet-stream in the entries table instead of video/mp4. But it still works when viewing in the browser, so not sure there.

Yeah, the current implementation puts whatever the client said at upload time in the database, but then it overrides blanks and `application/octet-stream` at download time. But in retrospect, that's confusing, so maybe the override should happen at upload time so that the `content_type` in the SQLite database will be what the user sees when they download.
