### ISSUE TITLE
Invalid shared Secret (Portainer and Nginx proxy manager)

### ISSUE THREAD

**Issue by PPTide** [mtlynch/picoshare#441]
I moved my picoshare instance to a different server (VM) and now it tells me `Invalid shared Secret`. (The page loads)

I've kept the same config in Nginx proxy manager and only changes the IP. The following is my Portainer Docker setup:
![Screenshot 2023-05-29 at 16 31 29](https://github.com/mtlynch/picoshare/assets/52575064/aeb875a4-f7f8-487a-b4e5-ba36ace627ba)

I would appreciate held and am happy to provide more info

**Comment by mtlynch** [comment]
The `PS_SHARED_SECRET` doesn't have any persistent state, so you can change it at any time and restart. It doesn't have to match what you used on your old server.

I can't think of any reason why you'd see different behavior for the same password on different servers. Is there something about the locale that would cause characters to be interpreted differently?

**Comment by PPTide** [comment]
I know there shouldn't be any difference. The local of the server now is just English US so idk why it would be interpreted differently...

**Comment by PPTide** [comment]
I didn't change anything and it just magically started to work xD
