### ISSUE TITLE
Allow chunked file transfers

### ISSUE THREAD

**Issue by sfleener** [mtlynch/picoshare#477]
I currently host a PicoShare instance behind a Cloudflare tunnel, which has a file transfer size limit of 100MB per request. I could use one of their paid plans or not use the tunnel at all, but neither of those is a particularly attractive option to allow larger file transfers.

A common workaround is [chunking the file transfer](https://community.cloudflare.com/t/does-the-100-mb-limit-apllies-to-all-users-on-my-website/297261/2) into multiple parts and reassembling it on the receiver's end. I'm not sure how involved a feature like this would be but I'd like to at least float the idea.

**Comment by kovmir** [comment]
Are there no solutions to this outside of this project?

**Comment by fuad00** [comment]
any updates on this?

**Comment by mtlynch** [comment]
No, unfortunately this falls outside [the scope of the project](https://github.com/mtlynch/picoshare?tab=readme-ov-file#picoshares-scope-and-future), as it seems to be only useful for Cloudflare tunnels, which I don't use.
