### ISSUE TITLE
Base URL for use behind reverse proxy

### ISSUE THREAD

**Issue by gibbotronic** [mtlynch/picoshare#483]
Is there any method of specifying the base URL for use behind a reverse proxy, eg. a HTTPS webserver serving picoshare on /share ? All of the URLs point back to the root, so after logging in it takes you to /

I know there's PS_BEHIND_PROXY but is there any configuration that lets me tell picoshare that is should prepend all URLs with /share/ ?

Thanks

**Comment by mtlynch** [comment]
I would think this would be something you'd configure at the proxy layer rather than in PicoShare.

If the reverse proxy is nginx, I believe the `proxy_pass` directive does this.
