### ISSUE TITLE
File does not upload

### ISSUE THREAD

**Issue by DanMundy** [mtlynch/picoshare#497]
## With version 1.3.7 and 1.3.8 running with Docker

On the upload tab,
I click "Choose a file",
browse for and select the file,
the file selection dialog is closed
but then nothing happens after that.

If I try to just drag a file directly onto the "Choose a file" button,
it doesn't upload that file,
instead it just loads that file with the browser
(eg I was trying to upload an image, and the browser now just shows me the image).

The Files tab is empty, nothing was uploaded.

### Purged all Docker containers, deleted all data

I shut down the Docker container,
purged all files with `docker system prune`,
deleted the data directory,
and set up the container using 1.3.8 as a completely fresh install,
and it does the exact same thing.

And the same for 1.3.7, it still fails to upload.

### Reverted to 1.3.6
I reverted to 1.3.6 and now file upload is working again.
This bug appears to have been introduced after 1.3.6.

**Comment by mtlynch** [comment]
Thanks for reporting this! Do you see any errors in the browser's JavaScript console when this happens?

It could be some browser extension interfering. Do you see it if you try in a different browser or in an incognito browser window?

**Comment by mtlynch** [comment]
Closing due to non-response.

Feel free to reopen!
