### ISSUE TITLE
Cannot read, edit or delete a file when the guest link is deleted

### ISSUE THREAD

**Issue by TsuboiKlein** [mtlynch/picoshare#501]
I created a guest link, just for testing something.
I uploaded a file and deleted the link.
Since I deleted the link, I have not been able to read/open, edit or delete the file, and I got an error message: "_failed to retrieve entry_"

Screenshot:
![DuckDuckGo_2023-10-01_11-36-36](https://github.com/mtlynch/picoshare/assets/30030291/e925b8df-d26f-4bb6-b378-901b414cfe12)

System Info (If necessary):
Synology 718+
DSM 7.2.1-69057
Docker

**Comment by mtlynch** [comment]
Thanks for reporting this! I can reproduce this. The error message in the logs is:

```text
2023/10/01 15:29:53 download.go:32: error retrieving entry with id 4FgxWPDuqg: sql: Scan error on column index 6, name "guest_link_id": converting NULL to string is unsupported
```

It looks like we're not handling it properly when the guest link disappears but the entry remains.

I have a fix that seems to work, but I need to add some tests as well.

https://github.com/mtlynch/picoshare/pull/502
