### ISSUE TITLE
[Feat] Adding Elestio as Deployment method

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [mtlynch/picoshare#507]
Hey team,
I am Kaiwalya, Developer Advocate at Elestio. Elestio has been providing options of fully deploying and managing Picoshare application [as shown here](https://elest.io/open-source/picoshare). I think it would be a great idea if we can add it to official readme/documentation here.
In addition to this, if you are interested we provide collaboration opportunities with tools we support by revenue share upon addition of this method in docs. If you would like to collaborate, just shoot me an email at [kaiwalya@elest.io](mailto:kaiwalya@elest.io) :)

<img width="1426" alt="image" src="https://github.com/mtlynch/picoshare/assets/53310847/36ca68c4-ab82-41d2-99d6-6806f0e46042">

**Comment by mtlynch** [comment]
Thanks for contributing this, but I'm not able to verify this method without paying for elestio, so this is too much effort to accept.

**Comment by kaiwalyakoparkar** [comment]
Hey @mtlynch we would be happy to give free credits to you to verify the method. Please share your email you used to log into Elestio :D
