### ISSUE TITLE
Failed to retrieve entry

### ISSUE THREAD

**Issue by tiritibambix** [mtlynch/picoshare#510]
Hello.

I got 2 files I uploaded 2022-04-22 can't be accessed because picoshare `failed to retrieve entry`.
Next file I uploaded was 2022-04-29 and it works fine.

What would be the reason for taht and how can I fix it please ?

Thank you.

PS: here's what I find in the logs.

```
"GET /-Tzr5jnFZfR HTTP/1.1" 500 25

download.go:32: error retrieving entry with id Tzr5jnFZfR: sql: Scan error on column index 6, name "guest_link_id": converting NULL to string is unsupported
```

**Comment by mtlynch** [comment]
Thanks for reporting this! This was fixed in #502.

Updating to the latest release will fix this issue.
