### ISSUE TITLE
After sending the file there is no way to get a download link

### ISSUE THREAD

**Issue by AlexNikMak** [mtlynch/picoshare#511]
Hello I Am new here(git and docker)

My setup is:
HP dl380p G8
2x E5-2670v2
136 GB DDR3
Windows server 2022
Docker desktop  version 4.23.0
Nginx Proxy Manager

So I am hosting in docker picoshare and connecting to it via Nginx Proxy Manager. For some reason when I am trying to upload directly from server or via sheard link after uploading web ui frizes on File uploaded! Processing.![msg313470831-250909](https://github.com/mtlynch/picoshare/assets/138360871/4ee41840-3de6-4336-b54f-a57d5a86b3e7) After 2-4min web ui changes to this.![msg313470831-250915](https://github.com/mtlynch/picoshare/assets/138360871/d9792294-3ce1-41bb-a8ac-bf66c3bc8d9c) I can see file that i just uploaded after another 5 min in file tab

**Comment by mtlynch** [comment]
How large is the file you're uploading? PicoShare tends to have issues with large files.

Do you see any messages in your server logs or in the JavaScript console?

**Comment by AlexNikMak** [comment]
Sorry for long response. 
Right now I switched a solution, so I no longer using Picoshare.
Regarding files, I was trying to send 5-10gb files and several smaller files total size of which were 6-8gb. 
Regarding errors and logs, I did not check logs but docker compose file console did not show any.

**Comment by mtlynch** [comment]
Okay, thanks for the follow up. I think it's likely that 5-10 GB is just too large for individual files on PicoShare. I haven't tested files that large.
