### ISSUE TITLE
Litestream bucket region

### ISSUE THREAD

**Issue by jlelse** [mtlynch/picoshare#512]
I want to deploy PicoShare using Scaleway Containers. I got it running, but Litestream isn't working yet. According to [the Litestream docs for Scaleway](https://litestream.io/guides/scaleway/), I also need to set the region (in my case "nl-ams"). But even setting "LITESTREAM_REGION" doesn't resolve the error:

```
/data/store.db(s3): monitor error: AuthorizationHeaderMalformed: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'nl-ams'
```

Is there any other way to configure the region? I can't find any documentation about Litestream environment vars.

**Comment by jlelse** [comment]
It seems like there was a PR merged to set the Region in Litestream using env vars (https://github.com/benbjohnson/litestream/pull/374). But maybe it's not yet in 0.3.9. Can you update Litestream in the container?

**Comment by mtlynch** [comment]
>I can't find any documentation about Litestream environment vars.

There isn't a `LITESTREAM_REGION` defined anywhere in Litestream, but `litestream.yml` will respect any environment variables you have set, so if you add it to the Docker command (`--env "LITESTREAM_REGION=nl-ams"`), Litestream should pick it up if there's a `${LITESTREAM_REGION}` placeholder in your `litestream.yml`.

The name is arbitrary, so you could call it `--env "FOO=nl-ams"` and then put in your `litestream.yml` a line like `region: `${FOO}`.

How are you launching PicoShare currently?

**Comment by jlelse** [comment]
It seems like there once was such an env var, so that confused me, but eventually, I figured out that there was the yaml file. So, I think this issue can be closed.
