### ISSUE TITLE
SSO / Proxy Auth

### ISSUE THREAD

**Issue by prologic** [mtlynch/picoshare#514]
Are you open to this? I'd probably go with Proxy Auth. I'm interested in spinning this up locally for myself and a few colleagues behind [Authelia](https://github.com/authelia/authelia)

**Comment by prologic** [comment]
I would implement this similarly to what I did for phoenix here https://github.com/ordinary-dev/phoenix/pull/40

**Comment by mtlynch** [comment]
Sorry, can you share more details about what you have in mind? What would have to change in PicoShare to support this?

**Comment by Lord-ZuzurNC** [comment]
As a workaround you can still add a location on your reverse proxy entry for PicoShare, if you are behind a reverse proxy.

**Comment by mtlynch** [comment]
From reflecting on this a bit more, I'm afraid I'm going to close this as out of scope. I've written up a bit more about what I consider in scope for PicoShare:

https://github.com/mtlynch/picoshare#picoshares-scope-and-future

For something as sensitive as authentication, I'm reluctant to support a feature that I don't personally use.

**Comment by prologic** [comment]
No worries 🤗
