### ISSUE TITLE
files uploaded through guest-links never expire?

### ISSUE THREAD

**Issue by dst78** [mtlynch/picoshare#515]
Not sure if the display is wrong or this is actual behaviour:

The default file retention rate on my instance is 30 days. When I upload a file as admin and don't change the expiry setting, "30 days" is correctly displayed for the file.

But when I create a guest-link and use that to upload a file:

1. there is no option to select the expiry (I am fine with that)
2. the file list (back in admin view) shows the file expiry from the guest-link as "never"

I'd love a default behaviour where guest-link uploads are always limited to the default retention time. 

Alternatively: Have them chose a retention time similar to admin, but only up to the default value. Second alternative: No selection option for guests but a separate retention time setting for guest-links in the admin settings.

**Comment by Lord-ZuzurNC** [comment]
I don't understand your ticket.
guest URL are having expiration setting.
![image](https://github.com/mtlynch/picoshare/assets/90102166/892c8914-f5c4-41f0-a029-eac3fd4e552d)
Maybe your issue was older than the last update of PicoShare?

**Comment by Lord-ZuzurNC** [comment]
Oh I see, thanks for the reply. I'll try to replicate on my side tomorrow (I'm west europe time zone).

**Comment by mtlynch** [comment]
@dst78 - Yes, that's currently working as intended, though I understand it'd be convenient to be able to specify a default expiration for files that guests upload.

It's not something I'm likely to implement in the short term, but I'd accept a PR that implemented the functionality that allowed the admin to specify the expiration time for guest uploads.

**Comment by ados8** [comment]
Just discovered Picoshare and it's excellent.
This does have me scratching my head as to why guests can effectively override the admin power for expiry.

**Comment by popdo** [comment]
Picoshare is great, but the expiration time for files uploaded by visitors is always set to Never. I hope the visitor files can follow the expiration time set in the settings.

**Comment by Balk-Z** [comment]
@mtlynch If you create a new release this issue can be closed. I am also wondering if there is anything missing for a new release or why that didn't happen yet? (I am currently using a custom built image until you don't publish the new version)

**Comment by mtlynch** [comment]
@Balk-Z - There's no particular release schedule. I cut releases on a best-effort as I have time. I just [cut a release](https://github.com/mtlynch/picoshare/releases/tag/1.4.5) today, though. Thanks for your work on this!
