### ISSUE TITLE
v8 architecture not supported

### ISSUE THREAD

**Issue by xxcosita3czxx** [mtlynch/picoshare#527]
well, i try to run this on my rpi 4b and it says rhis in podman, so i think it will be relarively good idea to make it work on rpi's aswell

**Comment by xxcosita3czxx** [comment]
also tried to do it from source, but it say that embed and io/fs is not in goroot

**Comment by mtlynch** [comment]
Can you share more details about the failure you're seeing? Docker builds are available for arm64 (armv8), so it should just work out of the box:

![image](https://github.com/mtlynch/picoshare/assets/7783288/1bdca6a5-e5f0-49f5-b918-89bd03d2a91b)

It's also available as an arm64 single binary:

![image](https://github.com/mtlynch/picoshare/assets/7783288/81d9cfce-4b94-4c85-a7d9-aae802eb08f6)

**Comment by xxcosita3czxx** [comment]
well i tried podman
![Screenshot_2024-01-31-02-39-52-77_3aea4af51f236e4932235fdada7d1643](https://github.com/mtlynch/picoshare/assets/103898611/a41df044-2e83-4816-a4a2-6d8d74ba874d)

and teh source give error of missing embed and io/fs

**Comment by xxcosita3czxx** [comment]
but ill try dat binary

**Comment by xxcosita3czxx** [comment]
it works, thanks, but you could add also how to run a binary

**Comment by xxcosita3czxx** [comment]
it took me a while

**Comment by mtlynch** [comment]
It looks like you're using an unofficial Docker image (elestio/picoshare). This is mine:

https://hub.docker.com/r/mtlynch/picoshare/
