### ISSUE TITLE
"Can you add a feature? It's to restrict sharing to a certain domain."

### ISSUE THREAD

**Issue by topmask** [mtlynch/picoshare#544]
Only allowing links to be shared on Website A, preventing theft on other websites, similar to the restrictions found in object storage

Essentially, it means only permitting links to be shared on Website A, while preventing unauthorized linking on other websites, akin to the restriction features found in object storage

**Comment by mtlynch** [comment]
Thanks for the suggestion!

Unfortunately, that use case [falls outside of how I use PicoShare](https://github.com/mtlynch/picoshare?tab=readme-ov-file#picoshares-scope-and-future), so I wouldn't be able to implement that or accept it as a feature contribution.
