### ISSUE TITLE
Uploading large file causes no links to be generated, textless red banner error on upload page.

### ISSUE THREAD

**Issue by marshalleq** [mtlynch/picoshare#554]
This is 100% repeatable and does not happen for small files.  Eventually I discovered I can get the link by going to the files tab, though this is being hit by a severe performance bug as it shouldn't take minutes to display a web page with a few links on hit.

Screenshot of page after successfully uploading 14GB file (with re-routed tmp directory).  God help us when we get many of these large files.

<img width="1517" alt="Screenshot 2024-02-13 at 09 03 59" src="https://github.com/mtlynch/picoshare/assets/13308996/c0fe9014-17d8-4485-ba56-94c5f2f86dc8">

**Comment by mtlynch** [comment]
Thanks for reporting this!

I think this is captured under #355, but let me know if I'm mistaken.

Just to set expectations, PicoShare isn't designed to support files over 1 GB. It's not designed specifically for small files, but I know there are performance and robustness issues with larger files, but I haven't spent a lot of time investigating. 

I prioritize features and bugs based on [what I personally use PicoShare for](https://github.com/mtlynch/picoshare?tab=readme-ov-file#picoshares-scope-and-future), so I'm not likely to invest in supporting large files for a while, as I don't use PicoShare for large files.

If most of your files are larger than 1 GB, PicoShare is probably not the right tool. Or maybe you can solve it by throwing lots of CPU/RAM at it, but I'm not likely to implement a fix in software in the short-term.

**Comment by marshalleq** [comment]
I understand.  Hopefully you can get some help from the community then as I believe you have a niche product here that is sorely missing in the market.  ie picoshare is awesome!  And it's a shame to waste such awesomeness over what is probably a small thing for the right person to fix.

Often this kind of niche thing will get popular very fast - lets hope it does and you get the support you need.

Anyway that error isn't the same as it's not a performance issue, it's a bug that doesn't present the links.  I did however find [this](https://github.com/mtlynch/picoshare/issues/511) which does sound like the same thing.

**Comment by Coolykoen** [comment]
i find this very odd. Don't get me wrong, i understand your perspective, but if you aren't supporting files over 1GB (mine is also crashing for 700MB file) then can you please remove this line from the picoshare start page: "There are no restrictions on file type, size, or content." and also this line from the github: "No file restrictions: Unlike sites like imgur, Vimeo, or SoundCloud that only allow you to share specific types of files, PicoShare lets you share any file of any size."

i specifically downloaded it to save replays of games, seeing as the file sizes wouldn't be a problem haha.

**Comment by mtlynch** [comment]
@Coolykoen 

>i find this very odd. Don't get me wrong, i understand your perspective, but if you aren't supporting files over 1GB (mine is also crashing for 700MB file) then can you please remove this line from the picoshare start page: "There are no restrictions on file type, size, or content." and also this line from the github: "No file restrictions: Unlike sites like imgur, Vimeo, or SoundCloud that only allow you to share specific types of files, PicoShare lets you share any file of any size."

I get that it's frustrating to see 700 MB uploads fail, but that's a limitation of the server's resources, not an inherent limitation in PicoShare.

As a test, I spun up a Scaleway PRO2-L (32 CPU / 128 GB RAM), and I was able to upload an 11 GB file fine:

![image](https://github.com/mtlynch/picoshare/assets/7783288/526cfd60-d70d-47da-8af9-1547db4c5c10)

I'm sure there are ways to make PicoShare more efficient so that larger files work on smaller servers, but PicoShare demonstrably supports files up to 11 GB.

**Comment by marshalleq** [comment]
From what I found it does work, but it produces an error, shown in the first post, which is confusing.  I'd say there are probably a few different areas around it since @mtlynch has stated he doesn't use it for large files.  Nevertheless it would be nice to get a few of these errors fixed, because clearly a lot of people are coming here expecting it to work more seamlessly than it does.
