### ISSUE TITLE
Login Error With Special Charactors

### ISSUE THREAD

**Issue by PitchAbyss** [mtlynch/picoshare#555]
i included '@' and '$' in my password which creates issue while loggin in

`172.30.0.1 - - [18/Feb/2024:09:27:23 +0000] "GET /third-party/google-fonts/fonts/karla-v21-latin/karla-v21-latin-600.woff2 HTTP/1.1" 200 0`

**Comment by mtlynch** [comment]
How are you setting the password? It's likely that your terminal is substituting the `@` and `$` characters before they reach PicoShare.

The log message about fonts is not an error. It's just an expected log message that your browser requested fonts.

**Comment by PitchAbyss** [comment]
> How are you setting the password? It's likely that your terminal is substituting the `@` and `$` characters before they reach PicoShare.
> 
> The log message about fonts is not an error. It's just an expected log message that your browser requested fonts.


Then how should i set the password ? I am using like @dmin@p@ss 

Also i was trying to upload a zip of 30gb and it doesnt starts for me 

https://github.com/mtlynch/picoshare/assets/13099434/8294a771-e951-4666-8fbb-0b7ab79db301

**Comment by mtlynch** [comment]
>Then how should i set the password ? I am using like @dmin@p@ss

How are you setting the password? In a file? From the terminal?

>Also i was trying to upload a zip of 30gb and it doesnt starts for me

Large files aren't going to work without a lot of compute resources. See #355.
