### ISSUE TITLE
getting ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by Jirka135** [mtlynch/picoshare#562]
Hi im hosting picoshare on my ubuntu server 
Im running picoshare in docker 
Ports are setup correctly in Nginx reverse proxy and i have set up record in cloudflare dns
how can i fix this issue ? im running 5 more services along with picoshare and only picoshare have these issues.

**Comment by mtlynch** [comment]
PicoShare doesn't handle TLS termination, so this is unfortunately not something I can help with. This is an issue with your Nginx config.

These issues might be helpful:

https://github.com/mtlynch/picoshare/issues/361#issuecomment-1405326488

https://github.com/mtlynch/picoshare/issues/523
