### ISSUE TITLE
Can upload some files, cannot upload others.

### ISSUE THREAD

**Issue by rklol237** [mtlynch/picoshare#572]
I've just installed picoshare and it seems to not want to upload certain file types.

It uploads .zip, .jpg, .docx, etc. just fine; but I get a blank error whenever I try to upload .conf and .ipa files. In chrome, the .ipa file starts uploading but fails to proceed with any progress (in firefox, it just outright fails and just gives a blank error). I have tried with and without extensions and it gives the same result.

![image](https://github.com/mtlynch/picoshare/assets/70005399/07bd44f3-2da9-42ef-8ef0-40e3759c9267)

![image](https://github.com/mtlynch/picoshare/assets/70005399/f210729f-276e-4b50-b6fc-e11542dec7c4)

![image](https://github.com/mtlynch/picoshare/assets/70005399/e1d35e5a-d28f-4df5-be02-b73d622cb6f7)

The following is my compose.yaml. I'm not sure if I'm doing something wrong or anything. Thanks. (I only have port 443 open on my firewall in case that the problem.)

version: "3.2"
services:
  picoshare:
    image: mtlynch/picoshare
    environment:
      - PORT=4001
      - PS_BEHIND_PROXY=true
      - PS_SHARED_SECRET=poop # Change to any password
    ports:
      - 4001:4001
    command: -db /data/store.db
    volumes:
      - /data:/data
networks: {}

**Comment by rklol237** [comment]
Some more images from firefox and dockge:
![image](https://github.com/mtlynch/picoshare/assets/70005399/348b642b-51e7-4a97-ab5c-7a3d243c6755)
![image](https://github.com/mtlynch/picoshare/assets/70005399/bef1ae7a-6f46-4e71-a0a7-1cbd64efe7f9)

**Comment by rklol237** [comment]
Some more images from firefox and dockge: (only the .conf file seems to produce an error on firefox and docker, uploading the ipa file doesn't even produce any error in both)

![333876100-786cf497-ed1e-4f90-87a6-ce3e92e54a79](https://github.com/mtlynch/picoshare/assets/70005399/ba5e7f92-24ac-4ae8-bd2c-8fd441f916e1)
![333876103-d7fed252-f06c-497d-b2d7-eb49cae423e3](https://github.com/mtlynch/picoshare/assets/70005399/296f9284-e9e5-4456-896e-241370e5e3f5)
![333876107-c4f5ebf6-8d55-46b5-853c-e3ba15639337](https://github.com/mtlynch/picoshare/assets/70005399/19a5a45d-fe00-4853-a209-39403f184d0a)

![333875544-bef1ae7a-6f46-4e71-a0a7-1cbd64efe7f9](https://github.com/mtlynch/picoshare/assets/70005399/4d97cfce-c5bc-4965-ad88-b8ff9eba81de)

**Comment by mtlynch** [comment]
Thanks for reporting this!

Can you share examples of the files that fail?

I tried uploading a `.conf` file, and it worked fine, so I'm wondering if it's something specific to your file:

![image](https://github.com/mtlynch/picoshare/assets/7783288/8a4d13a2-7090-4bf9-a254-2505efffe6a9)

**Comment by rklol237** [comment]
I just found that the file was empty, and notepad++ saved my edits to cache, which is probably why it didn't upload.

Is there a hard limit of 100MB in picoshare? Here is the ipa file that I wanted to upload to create a direct link for appdb sideloading. https://www.dropbox.com/scl/fo/2lcbnr27nqxtsvsd8pc3y/AOlaGYGEbgZ5AHyI8hpf62M?rlkey=cgmlf0k32tmzvsgkzi4pzcn20&st=l8ifkkg8&dl=0

**Comment by rklol237** [comment]
https://github.com/mtlynch/picoshare/assets/70005399/a36c9418-8509-47bc-8b4d-ed3de517a9e9

**Comment by rklol237** [comment]
https://github.com/mtlynch/picoshare/assets/70005399/b5c60578-f881-47e5-9d22-c72446c95067

**Comment by mtlynch** [comment]
Thanks for sharing the `yt.ipa` file. I was able to upload that successfully on my dev server.

Do you see any errors in the server logs when the upload fails? You shared server logs [previously](https://github.com/mtlynch/picoshare/issues/572#issuecomment-2132190122) that showed the file empty error, but do you have logs for when the `yt.ipa` fails?

The empty error was fixed in #556, but I haven't cut a release that includes that fix yet.

**Comment by rklol237** [comment]
From memory, I don't think the server spat out any error, it only displayed that the web page was accessed, I'll try again later today.

**Comment by rklol237** [comment]
I started picoshare on a local server and it seems to be working perfectly:
![Screenshot 2024-05-29 164701](https://github.com/mtlynch/picoshare/assets/70005399/1e467079-f5e4-4cad-9eca-f51f10ffc5a9)

However, on my Hetzner VPS, I get the blank error or a upload stall on Windows, iOS and MacOS.
I did manage to get an actual error message on my Linux machine:
![Screenshot from 2024-05-29 16-31-51](https://github.com/mtlynch/picoshare/assets/70005399/2d6f8562-1562-42c7-b819-bfb10557a0a4)

During all this, the docker terminal (on the VPS) didn't spit out any error message:
![Screenshot 2024-05-29 162444](https://github.com/mtlynch/picoshare/assets/70005399/da1aea29-abbf-48cb-91b1-ddb5c25545ab)

**Comment by rklol237** [comment]
When I also try to access my local picoshare through https, (via Cloudflare tunnels), it also errors out similarly to the one on my VPS.

**Comment by rklol237** [comment]
Nevermind, I just found out that Cloudflare has a upload limit of 100MB on the free tier. Thanks for the support anyways.

**Comment by mtlynch** [comment]
Okay, thanks for letting me know!

**Comment by gabrySerra** [comment]
> Nevermind, I just forgot that Cloudflare has a upload limit of 100MB on the free tier. I have changed my nameservers and now it works perfectly. Thanks for the time and support anyways.

Which nameserver are you using now?
I have the same problem with Cloudflare free plan

**Comment by rklol237** [comment]
> > Nevermind, I just forgot that Cloudflare has a upload limit of 100MB on the free tier. I have changed my nameservers and now it works perfectly. Thanks for the time and support anyways.
> 
> 
> 
> Which nameserver are you using now?
> 
> I have the same problem with Cloudflare free plan

I currently have all my domains registered with Porkbun Domains. The default nameservers also apparently uses Cloudflare, just without all the proxy features, etc. So I have been hosting picoshare on another domain that's still using the default Porkbun nameservers.

They are decently priced too, in my opinion, second to only cloudflare itself, and supports a ton of TLD's. I can highly recommend them.
