### ISSUE TITLE
Why the guest upload api returns uncertain responses? 

### ISSUE THREAD

**Issue by XiaoQiu2451** [mtlynch/picoshare#596]
Hello, I tried to use it as the main Image Host Service in my project.
Then I found a problem that the guest upload api returns uncertain responses.
Sometimes it returns JSON-like {'id': '...'}, sometimes it returns HTTP_URL like http://127.0.0.1:4001/-...
I am confused why it is designed in this way which has no any adventage for development.
And also, I think it will be better of this project to have a more clear API documents for development.

**Comment by mtlynch** [comment]
Can you share the steps that reproduce this behavior?

>And also, I think it will be better of this project to have a more clear API documents for development.

The project doesn't have a stable API, as it's [a hobby project](https://github.com/mtlynch/picoshare?tab=readme-ov-file#picoshares-scope-and-future) I work on for fun in my spare time.

**Comment by mtlynch** [comment]
Closing due to lack of response.
