### ISSUE TITLE
Please add a chunk size to help cloudflare users

### ISSUE THREAD

**Issue by Compukid** [mtlynch/picoshare#600]
I am hosting a few apps online and picoshare is a new one. I wanted to share files with others, but since I use cloudflare I'm running into the 100mb limit, which is frustrating. I also host nextcloud, but nc has a config called maxchuncksize, and by setting that to less than 100mb, it tricks cloudflare into thinking there are a bunch of small files instead.  Is there a possibility that picoshare can implement this as well?
Or any feature to help cloudflare users would be appreciated.

**Comment by mtlynch** [comment]
Thanks for reporting this!

Unfortunately, Cloudflare-specific fixes fall outside the scope](https://github.com/mtlynch/picoshare?tab=readme-ov-file#picoshares-scope-and-future) of what I can support in the project.
