### ISSUE TITLE
Writing to the database is slow after uploading a large file

### ISSUE THREAD

**Issue by magicindex** [mtlynch/picoshare#607]
Writing to the database is slow after uploading a large file：
1. I uploaded a 4.92G file and it was uploaded quickly, but the system kept waiting in circles. At this time, I found that the database was growing little by little. It took a long time to show up in files. Is this normal?
2. I saw that the database cannot be automatically reduced after it grows. Can I add a scheduled scan to automatically clean up the remaining space in the database?
------------------------------------
上传大文件后向数据库中写入很慢
1、上传了一个4.92G的文件，很快就传完，但是系统一直在转圈等待，这个时候发现数据库正在一点一点增长。等了很长时间才在files里面显示出来，这个是否正常现象。
2、看到有数据库增长后不能自动缩小的情况，能不能增加定时扫描自动清理数据库剩余空间。

**Comment by mtlynch** [comment]
Thanks for reporting this!

>I uploaded a 4.92G file and it was uploaded quickly, but the system kept waiting in circles. At this time, I found that the database was growing little by little. It took a long time to show up in files. Is this normal?

Yes, this is a known issue: https://github.com/mtlynch/picoshare/issues/355

There is a possible fix in https://github.com/mtlynch/picoshare/pull/567 but I haven't had time to finish that work. That would potentially improve performance and make large files usable.

>I saw that the database cannot be automatically reduced after it grows. Can I add a scheduled scan to automatically clean up the remaining space in the database?

I used to have this, but it ended up causing a lot of headaches (https://github.com/mtlynch/picoshare/pull/532), so I no longer would take a PR that added it back, but you could write a cronjob outside of PicoShare that regularly compacts the database.
