### ISSUE TITLE
【Request a feature】Added stack (tag) and search capabilities.

### ISSUE THREAD

**Issue by magicindex** [mtlynch/picoshare#608]
1. Add a stack (label) function, which is similar to adding a label to the uploaded file, and files with the same label form a stack. This allows you to quickly find files of the same type or package.
2. Hopefully, a search function can be added. Both of these are for more efficient file management.
------------------------
1、增加堆栈（标签）功能，类似于对上传文件打上一个标签，相同标签的文件形成一个堆栈。这样可以快速查找同类或者同包裹的文件。
2、希望可以增加一个搜索功能。这两个都是为了更高效的管理文件。

**Comment by magicindex** [comment]
Also looking forward to this feature ，Multiple file upload is a standard feature.

**Comment by mtlynch** [comment]
Thanks for this suggestion, but this wouldn't fit into my workflows, so it falls [out of scope of the project](https://github.com/mtlynch/picoshare?tab=readme-ov-file#picoshares-scope-and-future).
