### ISSUE TITLE
Guest files uploaded with a file lifetime expiry of "never" show 36500days in the files overview

### ISSUE THREAD

**Issue by Balk-Z** [mtlynch/picoshare#618]
@mtlynch  The last point standing was regarding the file index/info when the file expiration time is set to FileLifetimeInfinite. As FileLifetimeInfinite is not equal to NeverExpire. See here:
![Screenshot from 2024-12-09 17-42-40](https://github.com/user-attachments/assets/b77f2158-b7b2-452c-a048-921d80e3a962)

I'd much rather have "Never" there, but unsure of how to implement that in the formatExpiration function for the upload views, maybe you have an idea.

**Comment by Balk-Z** [comment]
I don't think that will work as the file lifetime decreases with time. So after the file is uploaded it will display "Never" but only for that day, the next day it should show 36499 days. (If I am not mistaking)
Additionally we do not really have access to a FileLifetime instance in [this](https://github.com/mtlynch/picoshare/blob/master/handlers/views.go#L175-L182) part of the code.

**Comment by mtlynch** [comment]
Oh, here's what I mean:

https://github.com/mtlynch/picoshare/compare/convert-to-never-expire?expand=1

It shouldn't change to 364999 because `NeverExpire` is always 2999-12-31, and we already recognize that as a special case.

I think the fix should be pretty straightforward, and the heavier lifting is in adding tests to prevent this from regressing in the future.

**Comment by Balk-Z** [comment]
That‘s my point though. The fileLifetime for guest uploads is just stored as 100 years in the future from what ever the time is it was created. Not 2999-12-31.

**Comment by Balk-Z** [comment]
My first try failed gloriously: https://github.com/mtlynch/picoshare/pull/619
Probably due to me having no clue what I am doing there. My goal was to switch to the files overview and verify the uploaded filename is present and one of the table fields was Never. Apparently I failed at the moving to the files page step.

Is there a way to execute your e2e tests locally? (Looking at your ci/cd workflow file it's just starting playwright:v1.40.0-focal, mounting the repository, install dependencies and running e2e-test script. **Just running the script locally  results in a failure of everything for me**) 

Lastly: I do not think we need to cover `FileLifetimeInfinite` == `NeverExpire` in go as that should be covered by the first upload tests for guest files. ([see here](https://github.com/mtlynch/picoshare/blob/master/handlers/upload_test.go#L281-L291))

**Comment by mtlynch** [comment]
>Probably due to me having no clue what I am doing there. My goal was to switch to the files overview and verify the uploaded filename is present and one of the table fields was Never. Apparently I failed at the moving to the files page step.

Yeah, Playwright's got a bit of a learning curve.

Can you view the failed job on CircleCI?

https://app.circleci.com/pipelines/github/mtlynch/picoshare/1746/workflows/0f9a1947-1bd4-429c-8e82-b081efc3b8ba/jobs/10467

If you click the artifacts tab and then `e2e/playwright-report/index.html`, you get a pretty user-friendly report:

![image](https://github.com/user-attachments/assets/62e2b856-d662-49e2-b345-b641c2930260)

In this case, the test is trying to go to the files tab, but they're viewing PicoShare as a guest user who's not logged in, so they can't see that page.

The next test is a bit better about demonstrating what happens in the context of the admin user and what happens as the guest user:

https://github.com/mtlynch/picoshare/blob/b1b1fae61eee19d7ab8b29fda950b7221e2578c6/e2e/guest-links.spec.ts#L68

>Just running the script locally results in a failure of everything for me)

In general, it's helpful if you can share the exact error message you're getting.

I've updated `CONTRIBUTING.md`  to give more information about the e2e test dependencies. Does this help?

https://github.com/mtlynch/picoshare/blob/b1b1fae61eee19d7ab8b29fda950b7221e2578c6/CONTRIBUTING.md#run-e2e-tests

>Lastly: I do not think we need to cover FileLifetimeInfinite == NeverExpire in go as that should be covered by the first upload tests for guest files. ([see here](https://github.com/mtlynch/picoshare/blob/master/handlers/upload_test.go#L281-L291))

Hmm, if the behavior is currently wrong but the test for it is passing, then I'd say the test isn't covering it. 🙃 

We should have some sort of test that verifies the behavior at the Go level, as the Playwright tests are pretty slow and complex to get running, as you're seeing.

**Comment by Balk-Z** [comment]
Wow, I have never had so little fun and so little pride accomplishing something, but this works:
```js
  await page.getByRole("menuitem", { name: "Files" }).click();
  await expect(page.locator("[test-data-filename]").nth(0).locator("td").nth(5)).toHaveText("Never");
```
_(there is probably a better or proper way to do this, but frankly I hate playwright and JS. It took me ages to access the table row...)_
If I remove the logic returning NeverExpire from `ExpirationFromTime` the test actually fails and reports the 36500days.
&nbsp;

Looking at the Go tests I still would argue the test is correct (and please correct me if I am wrong once more):
The test grabs the `entry.Expires` time, which in our updated case is equal to `NeverExpire`. The function used to compare the `ExpirationTime` with the `FileLifetime` is:
```go
func convertExpirationTimeToFileLifetime(et picoshare.ExpirationTime) picoshare.FileLifetime {
	if et == picoshare.NeverExpire {
		return picoshare.FileLifetimeInfinite
	}
	delta := math.Round(time.Until(time.Time(et)).Hours() / 24)
	return picoshare.NewFileLifetimeInDays(uint16(delta))
}
```
Which accounts for the case that `ExpirationTime` could be `NeverExpire` and returns `FileLifetimeInfinite`. This might be sub-optimal behavior I guess but I do not see another way to compare the to different extremes (FileLifetimeInfinite&NeverExpire). Here is the small relevant part, maybe you have some more improvement ideas. [LINK](https://github.com/mtlynch/picoshare/blob/master/handlers/upload_test.go#L471-L484)

**Comment by mtlynch** [comment]
>Looking at the Go tests I still would argue the test is correct (and please correct me if I am wrong once more):

I'd say that if we can see that if `TestGuestUpload` reports passing tests even when we can see that `guestEntryPost` is returning incorrect results, then something is wrong. The test must be either incorrect or incomplete.

I think the issue in `TestGuestUpload` is that we kind of cheated with `convertExpirationTimeToFileLifetime`, and now it's coming back to bite us. That helper function effectively [duplicates the logic](https://testing.googleblog.com/2014/07/testing-on-toilet-dont-put-logic-in.html) of [`FileLifetime.ExpirationFromTime`](https://github.com/mtlynch/picoshare/blob/b86bc737c0683666119de492a5c061891322181f/picoshare/file_lifetime.go#L83-L85).

For example, if I run this test right now:

https://github.com/mtlynch/picoshare/blob/b86bc737c0683666119de492a5c061891322181f/handlers/upload_test.go#L281-L291

The entry that it returns has an expiration of `2124-11-16 19:55:46 +0000 UTC` (now + 100 years), which is incorrect because it should be `2999-12-31 00:00:00 +0000 UTC` (the special-case value of [`NeverExpire`](https://github.com/mtlynch/picoshare/blob/b86bc737c0683666119de492a5c061891322181f/picoshare/picoshare.go#L43)).

But the test still passes because `convertExpirationTimeToFileLifetime` converts `2124-11-16 19:55:46 +0000 UTC` to `FileIfetimeInfinite` and concludes that the handler returned the right thing, but it didn't.

### Proposed solution

My best idea to solve it is to update the testcases for `TestGuestUpload` to check the expiration time explicitly. For example, [this testcase](https://github.com/mtlynch/picoshare/blob/b86bc737c0683666119de492a5c061891322181f/handlers/upload_test.go#L387C1-L397C5) would become something like this:

```go
{
	description: "guest file expires in 1 day",
	guestLinkInStore: picoshare.GuestLink{
		ID:           picoshare.GuestLinkID("abcdefgh23456789"),
		Created:      mustParseTime("2022-01-01T00:00:00Z"),
		UrlExpires:   mustParseExpirationTime("2030-01-02T03:04:25Z"),
		FileLifetime: picoshare.NewFileLifetimeInDays(1),
	},
	guestLinkID: "abcdefgh23456789",
        currentTime: mustParseTime("2024-01-01T00:00:00Z"),
	status:      http.StatusOK,
        fileExpirationTimeExpected: mustParseTime("2022-01-02T00:00:00Z"),
},
```

I just added #622 so that you can override the `Clock` interface to handlers and set the server clock to any time you want, which should make it much easier to test this logic.

**Comment by Balk-Z** [comment]
> The entry that it returns has an expiration of `2124-11-16 19:55:46 +0000 UTC` (now + 100 years), which is incorrect because it should be `2999-12-31 00:00:00 +0000 UTC` (the special-case value of [`NeverExpire`](https://github.com/mtlynch/picoshare/blob/b86bc737c0683666119de492a5c061891322181f/picoshare/picoshare.go#L43)).

It should be NeverExpire, but that is currently (at the time you ran the test) not implemented. So the returned value `2124-11-16 19:55:46 +0000 UTC` is correct as that is what [FileLifetime.ExpirationFromTime](https://github.com/mtlynch/picoshare/blob/b86bc737c0683666119de492a5c061891322181f/picoshare/file_lifetime.go#L83-L85) returns. `convertExpirationTimeToFileLifetime` correctly identifies a fileLifetime of 100 years and approves the test.
**Nonetheless I do agree with you that the tests need to be improved and the cheating function `convertExpirationTimeToFileLifetime` should not be required/used.**

Now, if we were to use `ExpirationFromTime` and used the entry.Expires value, the initial tests still return successfully.
```go

if got, want := entry.Expires, tt.guestLinkInStore.FileLifetime.ExpirationFromTime(handlers.NewClock().Now().UTC()); got != want {
	t.Errorf("expiration=%v, want=%v", got, want)
}
```
The issues arise with the other two tests checking non NeverExpire values:
```text
--- FAIL: TestGuestUpload (0.02s)
    --- FAIL: TestGuestUpload/guest_file_expires_in_1_day (0.00s)
        /home/balkaneser/dev/picoshare/handlers/upload_test.go:472: expiration=2024-12-12 09:52:37 +0000 UTC, want=2024-12-12 09:52:37.651119081 +0000 UTC
    --- FAIL: TestGuestUpload/guest_file_expires_in_365_day (0.00s)
        /home/balkaneser/dev/picoshare/handlers/upload_test.go:472: expiration=2025-12-11 09:52:37 +0000 UTC, want=2025-12-11 09:52:37.653414006 +0000 UTC
```
The expiration times are quite close, but not exact.

Anyhow, I do get what you would like to see in the Go tests using `currentTime` and `fileExpirationTimeExpected` but I for the life of me can not figure out how I would set a time using the Clock interface you implemented in https://github.com/mtlynch/picoshare/pull/622. While working on this project I am learning that my Go knowledge is not as good as I thought.
**Would you be so kind to give me an example of how one would "override the Clock interface" to set a time?**

**Comment by Balk-Z** [comment]
I finally found some time to do the [required changes](https://github.com/mtlynch/picoshare/compare/4311156ca858b7b2bc0291fb3c1e10348bd7a95c..ae20fff3a6c91a3ad37fffcfe129b116ee462410).

Thanks for the clock demo code, I had the correct thing in mind but tried to use an unnamed struct in the test block which I couldn't make work for some reason.

You commented out most test cases, those are passing, should I still add the `currentTime` & `fileExpirationTimeExpected` to them for completeness?

**Comment by mtlynch** [comment]
>You commented out most test cases, those are passing, should I still add the currentTime & fileExpirationTimeExpected to them for completeness?

Yeah, the commented out tests were just me temporarily disabling them for demonstration of the mocking I had in mind.

Sure, adding `currentTime` & `fileExpirationTimeExpected` is a good idea!
