### ISSUE TITLE
Add a "never" expiration option

### ISSUE THREAD

**Issue by mtlynch** [mtlynch/picoshare#92]
The current max expiration is 1 year, but it would be good to have a "never" option for files that are meant to stay permanent.

**Comment by viktorpenelski** [comment]
Hi @mtlynch, I have a couple of potential implementations for a "never" option that may (or may not) be useful. I'm open to suggestions as well if you have a nicer idea in mind:
- https://github.com/mtlynch/picoshare/pull/124
- https://github.com/mtlynch/picoshare/pull/125

**Comment by mtlynch** [comment]
Fixed in #125
