### ISSUE TITLE
Add option for generating shortlinks to file index

### ISSUE THREAD

**Issue by mtlynch** [mtlynch/picoshare#99]
We only show the user the full link URLs when they initially upload a file. We should add an option in the table for copying the full link or short link URL to the clipboard for easy sharing:

![image](https://user-images.githubusercontent.com/7783288/159184570-a64f0da4-1778-456a-8e4e-078d7a40ddf2.png)

**Comment by dertuerke** [comment]
Is that okay? #113

**Comment by dertuerke** [comment]
@mtlynch can be closed?

**Comment by mtlynch** [comment]
@dertuerke - If you add `Fixes #99` to the PR description of #113, then this bug will auto-close when we merge it into master.

**Comment by dertuerke** [comment]
Yeah it's added all in the new PR

**Comment by mtlynch** [comment]
Fixed in #128
